<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ios</string>
		<string>ioscfg</string>
		<string>iostxt</string>
		<string>cisco</string>
	</array>
	<key>name</key>
	<string>IOS</string>
	<key>patterns</key>
	<array>

		<!-- NO -->
		<dict>
			<key>comment</key>
			<string>matches only the no and highlights in "error" style</string>
            <key>match</key>
            <string>^\s*no </string>
            <key>name</key>
            <string>invalid.illegal.ios</string>
        </dict>

		<!-- FIRST-LEVEL CONFIG -->
		<dict>
			<key>match</key>
			<string>^\w+-?(\w+)?</string>
			<key>name</key>
			<string>support.class.ios</string>
		</dict>

		<!-- SECOND-LEVEL CONFIG -->
		<dict>
			<key>match</key>
			<string>^\s{1,2}\w+\s+addr?e?s?s?</string>
			<key>name</key>
			<string>support.function.ios</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s{1,2}\w+-?(\w+)?</string>
			<key>name</key>
			<string>support.function.ios</string>
		</dict>

		<!-- THIRD-LEVEL CONFIG -->
		<dict>
			<key>match</key>
			<string>^\s{3,4}\w+-?(\w+)?</string>
			<key>name</key>
			<string>string.unquoted.ios</string>
		</dict>
		
	</array>

	<key>scopeName</key>
	<string>text.ios</string>
	<key>uuid</key>
	<string>f3ba50f0-2bad-48b7-9509-f6d72e353ddb</string>
</dict>
</plist>