<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfg</string>
		<string>log</string>
	</array>
	<key>name</key>
	<string>network</string>
	<key>patterns</key>
	<array>
		<!-- Custom fields by Yandy Ramire @IPyandy-->
		<dict>
			<key>match</key>
			<string>mac-list|key chain|^udld|^service|^boot|^username|^clock|mpls</string>
			<key>name</key>
			<string>support.class.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ip prefix-list|vrf|^vdc|^vpc|</string>
			<key>name</key>
			<string>support.class.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>router</string>
			<key>name</key>
			<string>support.class.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>redistribute</string>
			<key>name</key>
			<string>support.class.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>route-map</string>
			<key>name</key>
			<string>support.class.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>address-family</string>
			<key>name</key>
			<string>support.class.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ip pim|ip igmp</string>
			<key>name</key>
			<string>support.class.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>match</string>
			<key>name</key>
			<string>support.class.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^interface</string>
			<key>name</key>
			<string>support.class.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>tacacs-server|class-map|policy-map</string>
			<key>name</key>
			<string>support.class.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>spanning-tree|^feature|^vlan|tacacs|aaa|otv-isis|errdisable|otv</string>
			<key>name</key>
			<string>support.class.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>switchport|encapsulation</string>
			<key>name</key>
			<string>support.class.network</string>
		</dict>

		<!-- SUB CONFIGS -->

		<dict>
			<key>match</key>
			<string>prefix-list|udld|key-chain|[^0-9]\s*mode</string>
			<key>name</key>
			<string>constant.character.escape.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>prefix-list|site-vlan|allocate|[^(vpc)]domain</string>
			<key>name</key>
			<string>constant.character.escape.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[^vlan]\s*(add|remove)|peer-gateway|auto-recovery</string>
			<key>name</key>
			<string>constant.character.escape.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ip address|neighbor|delay|</string>
			<key>name</key>
			<string>constant.character.escape.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>channel-group|mtu|bfd|match|metric</string>
			<key>name</key>
			<string>constant.character.escape.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>police|line|[^(port)]type|</string>
			<key>name</key>
			<string>constant.character.escape.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>service instance|bridge-domain</string>
			<key>name</key>
			<string>constant.character.escape.network</string>
		</dict>

		<!-- Misc -->

		<dict>
			<key>match</key>
			<string>description|ldp|key|banner</string>
			<key>name</key>
			<string>string.unquoted.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>name|snmp-server|snmp|rmon|ntp|logging</string>
			<key>name</key>
			<string>string.unquoted.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>eigrp|ospf|bgp|lisp</string>
			<key>name</key>
			<string>string.unquoted.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>isis</string>
			<key>name</key>
			<string>string.unquoted.network</string>
		</dict>

		<!-- END Custom -->

		<dict>
			<key>match</key>
			<string>^\s*no </string>
			<key>name</key>
			<string>invalid.illegal.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>access-list</string>
			<key>name</key>
			<string>support.function.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>crypto </string>
			<key>name</key>
			<string>string.unquoted.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>any</string>
			<key>name</key>
			<string>string.unquoted.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>deny </string>
			<key>name</key>
			<string>support.constant.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>permit </string>
			<key>name</key>
			<string>constant.character.escape.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>object-group</string>
			<key>name</key>
			<string>markup.list.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>object</string>
			<key>name</key>
			<string>markup.list.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>host</string>
			<key>name</key>
			<string>markup.list.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!(.*)</string>
			<key>name</key>
			<string>comment.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>static</string>
			<key>name</key>
			<string>constant.numeric.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>tunnel-group</string>
			<key>name</key>
			<string>support.class.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>crypto</string>
			<key>name</key>
			<string>support.class.network</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+\.\d+\.\d+\.\d+</string>
			<key>name</key>
			<string>constant.network</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.network</string>
	<key>uuid</key>
	<string>f3ba50f0-2bad-48b7-9509-f6d72e353ddb</string>
</dict>
</plist>
